version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - auth_service
      - transaction_service
      - product_service

  auth_service:
    build:
      context: ./backend/auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules

  transaction_service:
    build:
      context: ./backend/transaction-service
    ports:
      - "3000:3000"
    volumes:
      - ./backend/transaction-service:/app
      - /app/node_modules
    
  product_service:
    build:
      context: ./backend/product-service
    ports:
      - "8001:8000"
    volumes:
      - ./backend/product-service:/var/www/html
      - /var/www/html/vendor
