version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - auth_service
      - transaction_service
      - product_service

  auth_service:
    build:
      context: ./backend/auth-service
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules

  transaction_service:
    build:
      context: ./backend/transaction-service
    volumes:
      - ./backend/transaction-service:/app
      - /app/node_modules
    
  product_service:
    build:
      context: ./backend/product-service
    volumes:
      - ./backend/product-service:/var/www/html
      - /var/www/html/vendor
    command: >
      sh -c "touch database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000"
